version: '3.9'

services:
  postgres:
    container_name: postgres-pdv
    image: postgres:latest
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: apipdv2024

    volumes:
      - postgres:/var/lib/postgresql/data

    ports:
      - '5432:5432'

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: api-pdv
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '5555:5555'
      - '9229:9229'
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

    depends_on:
      - postgres
volumes:
  postgres:
