version: '3.9'

services:
  DatabasePdv:
    container_name: postgres-pdv
    image: postgres:latest
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: apipdv2025

    volumes:
      - postgres:/var/lib/postgresql/data

    ports:
      - '5432:5432'

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - DatabasePdv

  api:
    container_name: api-pdv
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '5000:5000'
      - '5555:5555'
      - '9230:9230'

    volumes:
      - .:/usr/app:cached
      - /usr/app/node_modules

    env_file:
      - .env.production

    depends_on:
      - DatabasePdv
volumes:
  postgres:
